# Generated by Django 4.1.4 on 2022-12-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='Pos2',
        ),
    ]
