# Generated by Django 4.1.4 on 2022-12-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post2_delete_pos2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
        migrations.DeleteModel(
            name='Post3',
        ),
    ]
